# Generated by Django 4.2.7 on 2025-10-16 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_bookimage_delete_item_alter_book_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this book as featured on homepage'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 15, 13, 59, 11322, tzinfo=datetime.timezone.utc)),
        ),
    ]
