# Generated by Django 4.2.7 on 2025-10-23 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0004_cart_alter_coupon_valid_to_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 15, 51, 3, 270692, tzinfo=datetime.timezone.utc)),
        ),
    ]
